pacman: Disable download timeout
I experience regular failures due to timeout, for example:

  error: failed retrieving file 'libssh2-1.8.2-1-x86_64.pkg.tar.xz' from http://mirrors.kernel.org/archlinux :
  Connection timed out after 10001 milliseconds

The pacman manual mentions:

  --disable-download-timeout
    Disable defaults for low speed limit and timeout on downloads. Use this
    if you have issues downloading files with proxy and/or security gateway.

I do run a proxy most of the time, but even when I don't I still see
this issue. So let's disable this timeout.

Ref: <https://www.archlinux.org/pacman/pacman.8.html>

Signed-off-by: Arnaud Rebillout <arnaud.rebillout@collabora.com>